### ISSUE TITLE
This line has bug

### ISSUE THREAD

**Issue by caitaozhan** [shahrokh765/commons#1]
https://github.com/shahrokh765/commons/blob/26d0570263ac18536099ebd68994b0d52fbc8af0/Point.py#L16

You can fix it as: self.cartesian = self.get_cartesian()

**Comment by shahrokh765** [comment]
Are u sure?
It works fine for me. Can you tell me the bug?

**Comment by caitaozhan** [comment]
Pylint says
```
An attribute defined in Commons.Point line 16 hides this method pylint(method-hidden)
```
And I cannot call the function p.get_cartesian()

**Comment by shahrokh765** [comment]
Are you using python 3?

**Comment by caitaozhan** [comment]
Yes. Python 3.7

**Comment by caitaozhan** [comment]
Try run the updated Sensor.py:
```
import sys
sys.path.append('../')
from Commons.Point import Point

class Sensor:
    def __init__(self, loc:Point, cost: float, std: float):
        self.loc, self.rp, self.cost, self.std = loc, -float('inf'), cost, std

if __name__ == '__main__':
    p = Point(0, 1)
    print(p.get_cartesian())  # <-- here
```

```
python Sensor.py
```

**Comment by shahrokh765** [comment]
I can't do it right now; gimme an hour.

**Comment by shahrokh765** [comment]
run it without parentheses.
You actually don't need these files right now. These are used to create the
data set.

The ML algorithms files are "ML\SpectrumAllocationLinearRForLoop.m",
"ML\SpectrumAllocationNNForLoop.m", "ML\SpectrumAllocationLRForLoop.m",
"LinearNN.py", and "SVM_SVR.ipynb".
You can find a dataset in "ML\data\"
